var cultivation_manual={
    three_power:{
        name:"Three Power Breathing Method",
        description:"Used to train mind and body through qi ventilation, hard to reach the level of third master even if pratcticed for a lifetime.",
        rank:"3rd rate",
        effect:1/30,
        mastery:0,
    },
    iron_bone_forge: {
        name: "Iron Bone Forging Tempering",
        description: "A basic body-hardening method used by martial artists to strengthen bones and muscles.",
        rank: "3rd rate",
        effect: 1 / 28,
        mastery: 0,
    },
    flowing_river_qi: {
        name: "Flowing River Qi Cultivation",
        description: "A technique that mimics the ceaseless flow of a river, enhancing stamina and endurance.",
        rank: "2nd rate",
        effect: 1,
        mastery: 0,
    },
    blazing_sun_fist: {
        name: "Blazing Sun Circulation",
        description: "A martial breathing method that enhances internal heat, allowing for stronger strikes.",
        rank: "2nd rate",
        effect: 1.5,
        mastery: 0,
    },
    storm_wind_breathing: {
        name: "Storm Wind Breathing",
        description: "A method that channels the force of the wind, improving agility and reaction speed.",
        rank: "1st rate",
        effect: 2,
        mastery: 0,
    },
    heavenly_turtle_breathing: {
        name: "Heavenly Turtle Breathing",
        description: "A legendary technique that enhances longevity and internal qi resilience.",
        rank: "human grade",
        effect: 5,
        mastery: 0,
    },
    azure_dragon_method: {
        name: "Azure Dragon Body Refinement",
        description: "Harness the strength of the Azure Dragon to increase physical resilience and qi circulation.",
        rank: "master grade",
        effect: 8,
        mastery: 0,
    },
    phantom_shadow_steps: {
        name: "Phantom Shadow Steps",
        description: "A breathing technique that allows the user to move like a ghost, evading attacks effortlessly.",
        rank: "grand master grade",
        effect: 20,
        mastery: 0,
    },
    tyrant_king_qi: {
        name: "Tyrant King's Qi Manipulation",
        description: "A domineering technique that allows the user to suppress opponents with sheer presence.",
        rank: "earth grade",
        effect: 100,
        mastery: 0,
    },
    void_sky_breathing: {
        name: "Void Sky Breathing",
        description: "A mysterious method that refines qi to an ethereal state, granting immense power.",
        rank: "sky grade",
        effect: 100,
        mastery: 0,
    },
    celestial_ascent_method: {
        name: "Celestial Ascent Method",
        description: "A divine technique that allows one to break free from mortal limitations and ascend to the heavens.",
        rank: "heaven grade",
        effect: 200,
        mastery: 0,
    },
}