//sword
let basic_weapon_skills={
    slash:{
        name:"Slash",
        desc:"A slash is a sabber technique that is used to cut.",
        energy_cost:0,
        damage:10,
        element: null,
    },
    thrust:{
        name:"Thrust",
        desc:"A thrust is a technique that is used to thrust.",
        energy_cost:0,
        damage:10,
        element: null,
    },
    stab:{
        name:"Stab",
        desc:"A stab is a technique that is used to stab.",
        energy_cost:0,
        damage:10,
        element: null,
    },
    cut:{
        name:"Cut",
        desc:"A cut is a technique that is used to cut.",
        energy_cost:0,
        damage:10,
        element: null,
    },
    punch:{
        name:"Punch",
        desc:"A punch is a fist technique that is used to punch.",
        energy_cost:0,
        damage:10,
        element: null,
    },
    palm_strike:{
        name:"Palm Strike",
        desc:"A palm strike is a palm technique that is used to strike.",
        energy_cost:0,
        damage:10,
        element: null,
    },
    dagger_throw:{
        name:"Dagger Throw",
        desc:"A dagger throw is a dagger technique that is used to throw a dagger.",
        energy_cost:0,
        damage:10,
        element: null,
    },
    arrow_shot:{
        name:"Arrow Shot",
        desc:"An arrow shot is a bow technique that is used to shoot an arrow.",
        energy_cost:0,
        damage:10,
        element: null,
    },
    hidden_weapons_throw:{
        name:"Hidden Weapons Throw",
        desc:"A hidden weapons throw is a hidden weapons technique that is used to throw hidden weapons smeared with a bit of poison.",
        type:"hidden_weapons",
        energy_cost:0,
        damage:10,
        element: null,
    },
}