let third_rate_weapon_skills = {
    // Slash Variants
    water_slash: {
        name: "Tidal Slash",
        desc: "A powerful slash infused with water energy, striking like a crashing wave.",
        element: qi_types.water,
        energy_cost: 5,
        damage: 15,
        effect: "Soaks the enemy, making them more vulnerable to Electric attacks.",
    },
    electric_slash: {
        name: "Thunder Slash",
        desc: "A quick slash charged with electricity, shocking the opponent.",
        element: qi_types.electric,
        energy_cost: 7,
        damage: 18,
        effect: "Has a chance to paralyze the enemy for 1 turn.",
    },
    wood_slash: {
        name: "Vine Slash",
        desc: "A slash that extends thorny vines, cutting deep into the enemy.",
        element: qi_types.wood,
        energy_cost: 6,
        damage: 14,
        effect: "Has a chance to root the enemy, reducing movement.",
    },
    fire_slash: {
        name: "Blazing Slash",
        desc: "A fiery slash that scorches the target on impact.",
        element: qi_types.fire,
        energy_cost: 8,
        damage: 20,
        effect: "Applies Burn, dealing damage over time for 3 turns.",
    },
    earth_slash: {
        name: "Stone Slash",
        desc: "A slash reinforced with stone energy, delivering a crushing blow.",
        element: qi_types.earth,
        energy_cost: 5,
        damage: 16,
        effect: "Has a chance to knock the enemy down for 1 turn.",
    },

    // Thrust Variants
    water_thrust: {
        name: "Aqua Thrust",
        desc: "A forward thrust empowered by a surge of water.",
        element: qi_types.water,
        energy_cost: 6,
        damage: 16,
        effect: "Reduces enemy's attack power for 2 turns.",
    },
    electric_thrust: {
        name: "Lightning Thrust",
        desc: "A thrust imbued with lightning, delivering a shocking impact.",
        element: qi_types.electric,
        energy_cost: 7,
        damage: 18,
        effect: "Has a chance to paralyze the enemy for 1 turn.",
    },
    wood_thrust: {
        name: "Branch Thrust",
        desc: "A thrust using hardened wood energy to pierce the enemy.",
        element: qi_types.wood,
        energy_cost: 6,
        damage: 14,
        effect: "Roots the target, preventing movement for 1 turn.",
    },
    fire_thrust: {
        name: "Infernal Thrust",
        desc: "A thrust engulfed in flames, searing through armor.",
        element: qi_types.fire,
        energy_cost: 8,
        damage: 19,
        effect: "Applies Burn for 3 turns.",
    },
    earth_thrust: {
        name: "Quake Thrust",
        desc: "A thrust that channels seismic force, shaking the enemy.",
        element: qi_types.earth,
        energy_cost: 5,
        damage: 17,
        effect: "Reduces enemy defense for 2 turns.",
    },

    // Stab Variants
    water_stab: {
        name: "Torrential Stab",
        desc: "A precise stab that injects water pressure into the enemy.",
        element: qi_types.water,
        energy_cost: 5,
        damage: 15,
        effect: "Increases enemy energy cost for their next move.",
    },
    electric_stab: {
        name: "Storm Stab",
        desc: "A quick stab that delivers a concentrated lightning jolt.",
        element: qi_types.electric,
        energy_cost: 7,
        damage: 18,
        effect: "Has a chance to paralyze the enemy.",
    },
    wood_stab: {
        name: "Root Stab",
        desc: "A stab that causes roots to sprout from the wound.",
        element: qi_types.wood,
        energy_cost: 6,
        damage: 14,
        effect: "Roots the target, reducing speed for 2 turns.",
    },
    fire_stab: {
        name: "Ember Stab",
        desc: "A fiery stab that burns deep into the target.",
        element: qi_types.fire,
        energy_cost: 8,
        damage: 19,
        effect: "Applies Burn for 2 turns.",
    },
    earth_stab: {
        name: "Boulder Stab",
        desc: "A stab backed by the weight of the earth, crushing the enemy.",
        element: qi_types.earth,
        energy_cost: 5,
        damage: 16,
        effect: "Has a chance to reduce enemy attack power.",
    },

    // Cut Variants
    water_cut: {
        name: "Wave Cut",
        desc: "A slicing motion that rides a wave, washing over the enemy.",
        element: qi_types.water,
        energy_cost: 5,
        damage: 14,
        effect: "Reduces enemy evasion for 2 turns.",
    },
    electric_cut: {
        name: "Spark Cut",
        desc: "A swift cut that discharges a small spark on contact.",
        element: qi_types.electric,
        energy_cost: 7,
        damage: 17,
        effect: "Has a chance to shock the enemy.",
    },
    wood_cut: {
        name: "Leaf Cut",
        desc: "A fast cut infused with sharp leaves.",
        element: qi_types.wood,
        energy_cost: 6,
        damage: 13,
        effect: "Reduces enemy speed for 1 turn.",
    },
    fire_cut: {
        name: "Scorch Cut",
        desc: "A burning slice that leaves a charred wound.",
        element: qi_types.fire,
        energy_cost: 8,
        damage: 18,
        effect: "Applies Burn for 3 turns.",
    },
    earth_cut: {
        name: "Rock Cut",
        desc: "A heavy cut that hits with the force of a landslide.",
        element: qi_types.earth,
        energy_cost: 5,
        damage: 15,
        effect: "Reduces enemy defense for 1 turn.",
    },

    // Punch Variants
    water_punch: {
        name: "Wave Fist",
        desc: "A fist that carries the force of a tidal wave.",
        element: qi_types.water,
        energy_cost: 5,
        damage: 16,
        effect: "Reduces enemy attack speed for 1 turn.",
    },
    electric_punch: {
        name: "Volt Punch",
        desc: "A punch electrified with pure lightning energy.",
        element: qi_types.electric,
        energy_cost: 7,
        damage: 18,
        effect: "Has a chance to paralyze the target.",
    },
    wood_punch: {
        name: "Bark Fist",
        desc: "A punch reinforced with nature’s strength.",
        element: qi_types.wood,
        energy_cost: 6,
        damage: 14,
        effect: "Roots the target for 1 turn.",
    },
    fire_punch: {
        name: "Flame Punch",
        desc: "A punch covered in blazing fire, igniting anything in its path.",
        element: qi_types.fire,
        energy_cost: 8,
        damage: 20,
        effect: "Applies Burn for 3 turns.",
    },
    earth_punch: {
        name: "Boulder Punch",
        desc: "A punch as heavy as a falling rock.",
        element: qi_types.earth,
        energy_cost: 5,
        damage: 17,
        effect: "Has a chance to knock the enemy down for 1 turn.",
    },
    // Palm Strike Variants
    water_palm_strike: {
        name: "Flowing Palm Strike",
        desc: "A palm strike that flows like water, redirecting the enemy's force.",
        element: qi_types.water,
        energy_cost: 6,
        damage: 15,
        effect: "Reduces enemy attack speed for 2 turns.",
    },
    electric_palm_strike: {
        name: "Thunder Palm Strike",
        desc: "A palm strike charged with electricity, delivering a shocking impact.",
        element: qi_types.electric,
        energy_cost: 8,
        damage: 18,
        effect: "Has a chance to paralyze the enemy for 1 turn.",
    },
    wood_palm_strike: {
        name: "Verdant Palm Strike",
        desc: "A palm strike infused with nature’s energy, disrupting enemy movement.",
        element: qi_types.wood,
        energy_cost: 7,
        damage: 14,
        effect: "Roots the enemy, reducing movement for 1 turn.",
    },
    fire_palm_strike: {
        name: "Scorching Palm Strike",
        desc: "A fiery palm strike that sears upon impact.",
        element: qi_types.fire,
        energy_cost: 9,
        damage: 20,
        effect: "Applies Burn, dealing damage over 3 turns.",
    },
    earth_palm_strike: {
        name: "Mountain Palm Strike",
        desc: "A heavy palm strike that strikes with the force of an avalanche.",
        element: qi_types.earth,
        energy_cost: 6,
        damage: 17,
        effect: "Has a chance to knock down the enemy for 1 turn.",
    },

    // Dagger Throw Variants
    water_dagger_throw: {
        name: "Aqua Dagger Throw",
        desc: "A thrown dagger that travels with the speed of flowing water.",
        element: qi_types.water,
        energy_cost: 5,
        damage: 14,
        effect: "Soaks the enemy, making them more vulnerable to Electric attacks.",
    },
    electric_dagger_throw: {
        name: "Volt Dagger Throw",
        desc: "A dagger infused with lightning, shocking the enemy on impact.",
        element: qi_types.electric,
        energy_cost: 7,
        damage: 17,
        effect: "Has a chance to paralyze the enemy.",
    },
    wood_dagger_throw: {
        name: "Thorn Dagger Throw",
        desc: "A dagger coated with thorny vines that pierce deeply.",
        element: qi_types.wood,
        energy_cost: 6,
        damage: 13,
        effect: "Roots the enemy, slowing them down for 1 turn.",
    },
    fire_dagger_throw: {
        name: "Blazing Dagger Throw",
        desc: "A burning dagger that leaves behind a scorching wound.",
        element: qi_types.fire,
        energy_cost: 8,
        damage: 19,
        effect: "Applies Burn for 2 turns.",
    },
    earth_dagger_throw: {
        name: "Stone Dagger Throw",
        desc: "A dagger made of compressed earth, striking like a rock.",
        element: qi_types.earth,
        energy_cost: 5,
        damage: 16,
        effect: "Has a chance to reduce enemy defense for 1 turn.",
    },

    // Arrow Shot Variants
    water_arrow_shot: {
        name: "Torrential Arrow Shot",
        desc: "An arrow propelled by water energy, striking with the force of a waterfall.",
        element: qi_types.water,
        energy_cost: 6,
        damage: 15,
        effect: "Soaks the enemy, increasing Electric damage taken.",
    },
    electric_arrow_shot: {
        name: "Thunderbolt Arrow Shot",
        desc: "An arrow charged with lightning, electrocuting the enemy on impact.",
        element: qi_types.electric,
        energy_cost: 8,
        damage: 18,
        effect: "Has a chance to paralyze the enemy.",
    },
    wood_arrow_shot: {
        name: "Vine Arrow Shot",
        desc: "An arrow wrapped in vines, binding the target.",
        element: qi_types.wood,
        energy_cost: 7,
        damage: 14,
        effect: "Roots the target, preventing movement for 1 turn.",
    },
    fire_arrow_shot: {
        name: "Infernal Arrow Shot",
        desc: "A flaming arrow that ignites everything it touches.",
        element: qi_types.fire,
        energy_cost: 9,
        damage: 20,
        effect: "Applies Burn for 3 turns.",
    },
    earth_arrow_shot: {
        name: "Boulder Arrow Shot",
        desc: "A heavy arrow infused with earth energy, crushing upon impact.",
        element: qi_types.earth,
        energy_cost: 6,
        damage: 17,
        effect: "Has a chance to reduce enemy defense.",
    },

    // Hidden Weapon Throw Variants
    water_hidden_weapons_throw: {
        name: "Misty Hidden Weapons",
        desc: "A rapid throw of hidden weapons, shrouded in water mist.",
        element: qi_types.water,
        energy_cost: 5,
        damage: 13,
        effect: "Has a chance to obscure enemy vision, reducing accuracy.",
    },
    electric_hidden_weapons_throw: {
        name: "Storm Hidden Weapons",
        desc: "A barrage of hidden weapons, crackling with electricity.",
        element: qi_types.electric,
        energy_cost: 7,
        damage: 16,
        effect: "Has a chance to paralyze the enemy.",
    },
    wood_hidden_weapons_throw: {
        name: "Leaf Hidden Weapons",
        desc: "A flurry of sharp wooden projectiles coated in natural toxins.",
        element: qi_types.wood,
        energy_cost: 6,
        damage: 14,
        effect: "Roots the enemy, slowing their movement for 1 turn.",
    },
    fire_hidden_weapons_throw: {
        name: "Ember Hidden Weapons",
        desc: "A hidden weapons technique that launches burning projectiles.",
        element: qi_types.fire,
        energy_cost: 8,
        damage: 18,
        effect: "Applies Burn for 2 turns.",
    },
    earth_hidden_weapons_throw: {
        name: "Dust Hidden Weapons",
        desc: "A swift throw of stone-tipped weapons, hitting with solid force.",
        element: qi_types.earth,
        energy_cost: 5,
        damage: 15,
        effect: "Has a chance to reduce enemy agility.",
    },
};